pvp:
  # Значение PvP у игроков по умолчанию
  default-pvp-status: false
  timings:
    # Время в тиках, по истечении которого PvP дуэль считается заверщённой.
    pvp-force-finish: 6000 # 5m in ticks
    #   Время в тиках, по истечении которо игрок может выключить свой
    # PvP режим после включения.
    on-off-cool-down: 6000 # 5m in ticks
